class leela_conf:
    LR = 0.05
    GPU_NUM = 2
    BATCH_SIZE = 256
    POLICY_LOSS_WEIGHT = 1.0
    MSE_LOSS_WEIGHT = 1.0
    REGULARIZER_SCALE = 0.0001
    INFO_STEP_INTERVAL = 10
    EVAL_STEP_INTERVAL = 80
    RESIDUAL_FILTERS = 128
    RESIDUAL_BLOCKS = 6
    DATA_SIZE = 5000
    DATA_DIR = "./data"
    SAVE_DIR = "./save"
